/**
 * wavSMiTH Portfolio — videos.js
 * Ambience Design 전용 유튜브 영상 데이터베이스
 */

const ambienceVideos = [
  {"id":"1VCbJ6lY6KQ", "title":"[Ambience] Indoor Fireplace Ambience for Relaxing | 6 Hours"},
  {"id":"oXVEVuGyJwE", "title":"[Ambient] Crystal Cavern : Fantasy Soundscape with Magical Echoes | 6 Hours"},
  {"id":"BymwgKU2VeA", "title":"[Ambience] Sci-Fi Control Room : Futuristic Soundscape with Console Beeps | 6 Hours"},
  {"id":"91LPZUQISIs", "title":"[Ambient] Enchanted Forest : Magical Nature Soundscape for Relaxation | 6 Hours"},
  {"id":"-xRZin7vsig", "title":"[Ambience] Quiet Rainfall in a Moss-Covered Woods: Peaceful Nature Sounds | 6 Hours"},
  {"id":"7N025VMZszA", "title":"[Ambience] Dark Fantasy : Ashen Skies and Crimson Thunder | Mordor | 6 Hours"},
  {"id":"aOum1jE4An0", "title":"[Ambient] Polar Solitude: Silent Snow and Distant Auroras | 6 Hours"},
  {"id":"akVEcZl0nrM", "title":"[Ambient] Pastel Dreamscape | Lucid Dream : Fantasy Soundscape for Dreaming | 6 Hours"},
  {"id":"1h9Odv3PCDQ", "title":"[Ambient] Altar in the Demonic Cavern : Fantasy Soundscape for Dungeon Exploration | 6 Hours"},
  {"id":"pd96ebqGeaY", "title":"[Ambience] Console Room Noise: Soft Whirring and Static Noise for Focus | 6 Hours"},
  {"id":"g9ixH9v2Aus", "title":"[Ambience | No Music] Wukong : Meditation | Nature | Tundra, Snow Field | 6 Hours"},
  {"id":"aunqzf38fuw", "title":"[Ambience] Cybertron : Sci-Fi Planet | Transformer | 6 Hours"},
  {"id":"qdPtXZTPHV4", "title":"[Ambient] Welcome to Silent Hill : Haunted Streets | Eerie, Horrify Soundscape | 6 Hours"},
  {"id":"bHKCAxLqwcM", "title":"[Ambience | No Music] Wukong : Meditation | Nature | Mountain | 6 Hours"},
  {"id":"WHZHAxccwfk", "title":"[Ambient] Wukong : Pagoda Realm | Dark Cavern Soundscape | Horrify Echo | 6 Hours"},
  {"id":"ZRuBiPqarZc", "title":"[Ambience | No Music] Wukong : Meditation | Nature | Mountain | 6 Hours"},
  {"id":"4GSK_Z2UHoM", "title":"[Ambient] Cosmic Traveling: Captivating Nebula Atmosphere Soundscape"},
  {"id":"v8WGQVvCUNA", "title":"[Ambient] Scorched Lands: Lava Fields | Natural Soundscape for Virtual Exploration | 6 Hours"},
  {"id":"fAi-Toa-7PU", "title":"[Star Wars Ambience] Dagobah | Misty Forest Soundscape | 6 Hours"},
  {"id":"VkeQDxAUr1s", "title":"[Star Wars Ambience] Hoth : Rebel's Basecamp, Echobase | Blizzard Soundscape | 6 Hours"},
  {"id":"Gnd1mV4wrvk", "title":"[Ambience] Cosmic Traveling: Spaceship Cockpit Ambience with Engine & Signal Sounds | 6 Hours"},
  {"id":"93dm3Mtyj0I", "title":"[World of Warcraft Ambience] Khaz Algar : Azj Kahet | Underground Cavern | 6 Hours"},
  {"id":"brJxIgf7x0w", "title":"[World of Warcraft Ambience] Khaz Algar : Hallowfall | Nature Soundscape | 6 Hours"},
  {"id":"PS4EEb13eqU", "title":"Cozy Rainfall Through a Gloomy Window : Relaxing Ambience | 6 Hours"},
  {"id":"i_vD3j0T8Rg", "title":"[Star Wars Ambience] Star Wars Outlaw : Planet Akiva | Jungle Forest | 6 Hours"},
  {"id":"8lgDE_V0QGA", "title":"[World of Warcraft Ambience] Khaz Algar : The Ringing Deeps | Underground Furnace | 6 Hours"},
  {"id":"Wmyc-u-kIMA", "title":"[Star Wars Ambience] Star Wars Outlaw : Moon Toshara | Savanna | 6 Hours"},
  {"id":"DAEeOkzptLQ", "title":"[Music & Ambience] Wukong : Meditation | Chinese Flute Ambient | Nature | 6 Hours"},
  {"id":"wLAOwUq11UE", "title":"[World of Warcraft Ambience] Khaz Algar : Isle of Dorn | Dornogal | 6 Hours"},
  {"id":"U-8kOETlz1A", "title":"[Music & Ambience] Wukong : Meditation | Chinese Flute Ambient | Nature | 6 Hours"},
  {"id":"AwOanCoRtbY", "title":"[Music & Ambience] Wukong : Oriental Mountain Soundscape | 6 Hours"},
  {"id":"k8NM4C6xyHI", "title":"[Ambient] Underwater | Horrify echo sound | Full Fathom | 6 Hours"},
  {"id":"Le5LxthGBqk", "title":"[Star Wars Ambience] Kashyyyk : Wookiee's Planet | Jungle Soundscape | 6 Hours"},
  {"id":"o0JOZJH1ekA", "title":"[Star Wars Ambience] Kamino : Tipoca city | Ocean, Wave, Rain, Storm Soundscape | 6 Hours"},
  {"id":"P7Wl9lBZh-k", "title":"[Ambient] Alice Through the Looking Glass : Time Realm | The Chronosphere | Fairy Tale | 6 Hours"},
  {"id":"EMryfSftrdg", "title":"[Star Wars Ambience] Tatooine Night | Desert Soundscape | 6 Hours"},
  {"id":"GPMFoC4VG1k", "title":"[Music & Ambience] Alice in Wonderland : Mushroom Forest | Tulgey Wood | Fairy Tale | 6 Hours"},
  {"id":"qrgBfpG4prM", "title":"[Music & Ambience] Alice in Wonderland : White Queen's Castle | Marmoreal | Fairy Tale | 6 Hours"},
  {"id":"SEcMdppqJGc", "title":"[Music & Ambience] Alice in Wonderland : Red Queen's Garden Party at Salazen Grum | 6 Hours"},
  {"id":"GYZMFYsaADw", "title":"[Music & Ambience] You've just entered Wonderland : Fantasy Soundscape | Game OST | 1 Hour"},
  {"id":"J6UOyUDezKo", "title":"[Ambience] Nobody Wants to Die : Neo Noir Rooftop, Cyberpunk, Rainy Urban Soundscape | 6 Hours"},
  {"id":"PKH3S7HUmR4", "title":"[Music & Ambience] Nobody Wants to Die : Neo Noir, Cyberpunk, Synthwave Soundscape | 6 Hours"},
  {"id":"jW2BPCxyDhE", "title":"[Ambient] Desolation has come to Yharnam : Outdoor Ambience for Bloodborne Exploration | 6 Hours"},
  {"id":"v_D7LjIg3V8", "title":"[Music & Ambience] Hidden Temple of the Deep : Journey Beneath the Waves | Game OST | 1 Hour"},
  {"id":"w_62pdXNepM", "title":"[Music & Ambience] Mermaid Princess' Melodies : Fantasy Soundscape for Reverie | 6 Hours"},
  {"id":"ZpdV9QycRNI", "title":"[Ambience] Deap Blue Sea : Under Water soundscape for Virtual Exploration | 6 Hours"},
  {"id":"rgyAGxYFcZU", "title":"[Ambience] Coastal Gorge : Natural Soundscape for Virtual Exploration | 6 Hours"},
  {"id":"1kGgg3S21zg", "title":"[Ambience] Stormy Sea & Coastal Cliffside : Natural Soundscape for Virtual Exploration | 6 Hours"},
  {"id":"oYh3ay5CFlA", "title":"[Ambience] Lava Flow : Natural Soundscape for Virtual Exploration | 6 Hours"},
  {"id":"DWFB9UomCZA", "title":"[Ambient] Ethereal Aqua Grove : Mystical Soundscape for Meditation | 6 Hours"},
  {"id":"kUSQmHSj-VU", "title":"[Ambience] Server Room : Analog Noise Environment for Sleep | 6 Hours"},
  {"id":"wo7nXaFMNjc", "title":"[Music & Ambience] Dwarven Humming : A Song for Erebor | The Lord of the Rings | 6 Hours"},
  {"id":"4KUFw5eHpfw", "title":"[Music & Ambience] Luxurious Hotel Lobby : Calm Noise with Piano | Game OST | 1 Hour"},
  {"id":"25vxwwBlXbk", "title":"[Ambience] Rainy New York Streets : Urban Soundscape for Relaxation | 6 Hours"},
  {"id":"me2T2j85vJU", "title":"[Music & Ambience] Rainfall Outside the Hotel : Lofi Chill Beats for Relaxation | Game OST | 1 Hour"}
];
